package badass.calendar;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JCheckBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Swetal
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {        
        pr = week.getPeriods();
        initComponents();
        for (int i = 1; i < 6; i++){
            jTable1.getColumn(week.getDayName(i)).setCellRenderer(new ButtonRenderer());
            jTable1.getColumn(week.getDayName(i)).setCellEditor(
            new ButtonEditor(new JCheckBox(),pr));            
        }
        jTable1.getColumn("Period").setWidth(5);
        jTable1.repaint();
        loadLabels();
        
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        weekLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        previousWeekButton = new javax.swing.JButton();
        nextWeekButton = new javax.swing.JButton();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239,187,41));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WVHS Math Department Computer Lab Reservation");

        weekLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        weekLabel.setForeground(new java.awt.Color(239,187,41));
        weekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weekLabel.setText("Schedule for the week of " + week.getStartDate() + " - " + week.getEndDate());

        jTable1.setBackground(new java.awt.Color(0, 102, 0));
        jTable1.setForeground(new java.awt.Color(187,126,39));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"             1", null, null, null, null, null},
                {"             2", null, null, null, null, null},
                {"             3", null, null, null, null, null},
                {"             4", null, null, null, null, null},
                {"             5", null, null, null, null, null},
                {"             6", null, null, null, null, null},
                {"             7", null, null, null, null, null},
                {"             8", null, null, null, null, null}
            },
            new String [] {
                "Period", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(50);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18));
        jScrollPane1.setViewportView(jTable1);
        

        previousWeekButton.setText("Previous");
        previousWeekButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousWeekButtonActionPerformed(evt);
            }
        });

        nextWeekButton.setText("Next");
        nextWeekButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextWeekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(previousWeekButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextWeekButton))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousWeekButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weekLabel)
                            .addComponent(nextWeekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadLabels(){
        for(int i = 0;i<pr.length;i++){
            for(int c = 0;c < pr[i].length; c++){
                if(pr[i][c].hasReservation()){
                    String label = DatabaseManager.reservationmap.get(pr[i][c]).toString();
                    jTable1.getModel().setValueAt(label,c,i+1);
                }else{
                    jTable1.getModel().setValueAt("OPEN", c, i+1);
                }
            }
        }
    }
    /**
     * Shifts week to next week and shows the reserved periods for the next week
     * @param evt an ActionEvent
     */
    private void nextWeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextWeekButtonActionPerformed
        /* Replace following method with call to getPeriod for next week*/
        week.nextWeek();
        pr = week.getPeriods();
        weekLabel.setText("Schedule for the week of " + week.getStartDate() + " - " + week.getEndDate());
        loadLabels();
        
               
    }//GEN-LAST:event_nextWeekButtonActionPerformed
    
    /**
     * Shifts week to previous week and shows the reserved periods for the previous week
     * @param evt an ActionEvent
     */
    private void previousWeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousWeekButtonActionPerformed
        week.previousWeek();
        pr = week.getPeriods();
        weekLabel.setText("Schedule for the week of " + week.getStartDate() + " - " + week.getEndDate());
        loadLabels();
    }//GEN-LAST:event_previousWeekButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton nextWeekButton;
    private javax.swing.JButton previousWeekButton;
    private javax.swing.JLabel weekLabel;
    // End of variables declaration//GEN-END:variables
    //This attribute will manage the week displayed to user
    Week week = new Week();
    //ReservationMap map = new ReservationMap();
    Period[][] pr = new Period[5][8];
}

